DROP TABLE IF EXISTS 蔵書;

-- スキーマとオブジェクトをリセット
DROP SCHEMA IF EXISTS 蔵書 CASCADE;
CREATE SCHEMA 蔵書;

-- 蔵書リセット
CREATE TABLE 蔵書.書籍(
    本番号 INTEGER PRIMARY KEY,
    タイトル VARCHAR(40) NOT NULL,
    著者 VARCHAR(40) NOT NULL,
    登録日 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);