DROP TABLE IF EXISTS 会員,図書,蔵書,貸出可能,貸出,返却,予約,予約取消,取置,貸出と会員;
DROP SEQUENCE IF EXISTS 貸出ID;
DROP SEQUENCE IF EXISTS 予約ID;

-- スキーマとオブジェクトをリセット
DROP SCHEMA IF EXISTS 資料 CASCADE;
CREATE SCHEMA 資料;

DROP SCHEMA IF EXISTS 蔵書 CASCADE;
CREATE SCHEMA 蔵書;

DROP SCHEMA IF EXISTS 会員 CASCADE;
CREATE SCHEMA 会員;

DROP SCHEMA IF EXISTS 貸出 CASCADE;
CREATE SCHEMA 貸出;

DROP SCHEMA IF EXISTS 予約 CASCADE;
CREATE SCHEMA 予約;

DROP SCHEMA IF EXISTS 取置 CASCADE;
CREATE SCHEMA 取置;

-- 会員スキーマ
CREATE TABLE 会員.会員
(
    会員番号 INTEGER PRIMARY KEY,
    氏名   VARCHAR(40) NOT NULL,
    会員種別 VARCHAR(5)  NOT NULL,
    登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 資料スキーマ
CREATE TABLE 資料.図書
(
    資料番号  INTEGER PRIMARY KEY,
    タイトル VARCHAR(40) NOT NULL,
    著者   VARCHAR(40) NOT NULL,
    登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 蔵書スキーマ
CREATE TABLE 蔵書.蔵書
(
    蔵書番号 VARCHAR(40) PRIMARY KEY,
    資料番号  INTEGER   NOT NULL REFERENCES 資料.図書,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.貸出可能
(
    蔵書番号 VARCHAR(40) PRIMARY KEY REFERENCES 蔵書.蔵書,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.貸出中
(
    蔵書番号 VARCHAR(40) NOT NULL REFERENCES 蔵書.蔵書,
    登録日時 TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE 蔵書.取置中
(
    蔵書番号 VARCHAR(40) PRIMARY KEY REFERENCES 蔵書.蔵書,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
